# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Azure DevOps pipeline!
  displayName: 'DBA42'
- task: TerraformInstaller@0
  displayName: 'Installing Terraform'
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  displayName: 'Intializing Terraform'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'S2-Visual Studio Ultimate with MSDN(2)(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'
    backendAzureRmResourceGroupName: 'S2-RG-DevOps'
    backendAzureRmStorageAccountName: 's2storageaccountdevops42'
    backendAzureRmContainerName: 's2containerdevops42'
    backendAzureRmKey: 'tf/terraform.tfstate'